### ISSUE TITLE
nintendo joy-cons support

### ISSUE THREAD

**Issue by polltu200** [Timocop/PSMoveServiceEx-Virtual-Device-Manager#10]
Hello, it would be nice to add support for both joy-cons (left and right) with the led balls to use it like a real psmove controllers.

**Comment by Timocop** [comment]
I do not own the Hardware so for now this will not happen. Unless i add a plugin system to VDM (which is already planed) and someone else adds it.

**Comment by polltu200** [comment]
thanks for the information, then I'll wait for the plugin system.
