### ISSUE TITLE
OSC Timeout - Don't connect my OSC server

### ISSUE THREAD

**Issue by PedroN222** [Timocop/PSMoveServiceEx-Virtual-Device-Manager#13]
My OSC server not connect, just stay OSC timeout, i didn't found anything about this, may someone help me?
![image](https://github.com/Timocop/PSMoveServiceEx-Virtual-Device-Manager/assets/61709045/c348ec3f-c70d-402c-8ead-69875dc7f298)

**Comment by Timocop** [comment]
- Make sure SteamVR driver is installed.
- Make sure SteamVR is running and ``psmsex`` addon running.
- Check your Firewall, disable it if neseccary.
- If everything fails, put the VDM folder in ``C:\`` instead. and try again.
