### ISSUE TITLE
How can i adjust controller offsets?

### ISSUE THREAD

**Issue by Agusseq** [Timocop/PSMoveServiceEx-Virtual-Device-Manager#14]
The controllers are showing way above of my head, so i was trying to set the offset but i can't find any option for that.
Like Driver4VR that has an offset option, where you can move X, Z or Y in real time of the virtual controllers that are on the SteamVR

**Comment by Timocop** [comment]
If you use a 3-DoF HMD, you can go **Config Tool > Tracker Settings > Playspace Offsets**. If you use a 6-DoF however tracking by PSMoveServiceEx you need properly setup the optical tracking.
