### ISSUE TITLE
Version 13.4 broke virtual controller in steamvr

### ISSUE THREAD

**Issue by zedzad14** [Timocop/PSMoveServiceEx-Virtual-Device-Manager#19]
In "Virtual Motion Tracker" section and "Trackers" tab it does show up virtual controllers position and rotation
![image](https://github.com/user-attachments/assets/463e2a10-7c63-4a54-8b67-54bd39271215)
while in "Management" tab it doesn't have any position or rotation and in steamvr, tracker is not seen anywhere
![PSMSVirtualDeviceManager_N231TTETu6](https://github.com/user-attachments/assets/dc9776f6-632c-4f08-a2e2-70ecc4038d02)

**Comment by Timocop** [comment]
If you have SteamVR overrides enabled, make sure it is not overwriting itself.
Also please share your logs via **Logs and diagnostics**

**Comment by zedzad14** [comment]
I had previously tried using steamvr overrides to override HMD orientation and position, although, in those screenshots I already had disabled them. Here are the logs with just the HMD and TRACKER in the "Management" tab while the issue still persists
[combined_logs.txt](https://github.com/user-attachments/files/17265579/combined_logs.txt)

**Comment by Timocop** [comment]
For some reason, looking at your logs, the recenter orientation of your tracker is ``NaN``. Please clear all recenter data for all trackers in VDM. Go **VDM > Virtual Motion Tracker > Trackers > (select a tracker) > Recenter... > Reset**

**Comment by zedzad14** [comment]
Thanks,
