### ISSUE TITLE
How accurate is XYZ tracking and hand rotation?

### ISSUE THREAD

**Issue by oxysoft** [Timocop/PSMoveServiceEx-Virtual-Device-Manager#2]
Hi, I am looking to potentially get PS Move controllers for a creative coding project where I will control an image with my hands, those remotes looks very appropriate. I'm not too familiar with how they work, it looks like the depth perception is achieved through a 3D camera and some maths to compare the colored orbs. If I'm understanding correctly, you have re-implemented the logic that takes the camera images and calculates these positions? Do you know how accurate this is, i.e can it pick up slight movements at the centimeter scale for all 3 axes? And I assume the origin of the position is the camera? And the polling rate, 60hz or more I hope?

Thanks!

**Comment by Timocop** [comment]
PSMoveService is for 3D applications like VR (example [here](https://www.youtube.com/watch?v=8pwCMh_Z4ko)). If you want to use PSmoves for simple projects you may want to use [PSmoveAPI](https://github.com/thp/psmoveapi) instead. It simpler to setup.

#

 > ... looks like the depth perception is achieved through a 3D camera ...

Tracking is done by triangulation with multiple normal RGB cameras not 3D cameras. Which is the most precise but require pose calibration to setup cameras in 3D space.
If you use one camera, Ball size measurement is done, which is the most inaccurate method but works without calibrating pose.
If you want more details about this go to the legacy PSMS wiki.

**Comment by Timocop** [comment]
Do you have other questions? Otherwise i will close this.
