### ISSUE TITLE
virtual devices calibration

### ISSUE THREAD

**Issue by MCLIX59** [Timocop/PSMoveServiceEx-Virtual-Device-Manager#20]
I can't normally calibrate virtual trackers with virtual controllers. When i try to calibrate with virtual controllers and LED's the virtual trackers are in one place in the psmoveservice ex
![image](https://github.com/user-attachments/assets/2c7610bb-c30c-4dbd-9d64-04ee5ca469d2)
How to get it calibrated if ps move controllers aren't cheap in my country

**Comment by Timocop** [comment]
What exactly are you trying to do because i have no idea.

**Comment by MCLIX59** [comment]
When i am trying to do a calibration with two virtual cameras and an led ping pong ball then after calibration virtual cameras are stuck in on place and virtual controller can only rotate

1. Phone with movetrackvr app is on table horizontally while calibrating
2. I am calibrating on a4 paper
3. There are small space between cameras on table
4. Cameras are on table and watching on each other

**Comment by Timocop** [comment]
Please upload your logs using **VDM Logs and Diagnostics** feature.

If you have just 2 cameras, they are not supposed to watch each other. You will have problems with triangulation blind spots. Its better to have the in the front facing you.

**Comment by MCLIX59** [comment]
I'm very sorry! Everything is alright, i just moved my cameras and everything works well. Thank you for app

**Comment by longmelf** [comment]
Good day. What controllers are you using?
