### ISSUE TITLE
PSMoveService

### ISSUE THREAD

**Issue by longmelf** [Timocop/PSMoveServiceEx-Virtual-Device-Manager#21]
Good day, I am asking for help. I am asking for a link to the new instruction. I have been trying to set up psmovie controllers for the third year now. I don't have them moving.
![image](https://github.com/user-attachments/assets/df249e4b-044c-4bba-b3c2-93d41d2fd13a)
![image](https://github.com/user-attachments/assets/01887ca0-1e03-426b-b5e3-28d96d6b2a39)
![image](https://github.com/user-attachments/assets/3f3517fc-f302-4d0a-a7f1-f0f06cf76c44)

**Comment by Timocop** [comment]
What exactly are you trying to do? Whats is your goal? You posted no useful information what the actual issue is.
For Driver4VR related issues and help contact the Driver4VR developer.

**Comment by SupertoineFR** [comment]
https://steamcommunity.com/app/1366950/discussions/0/4625852883021115627/?tscn=1730314602
issue moved here
